export enum PermissionStatus {
    CHECKING = 'CHECKING',
    GRANTED = 'GRANTED',
    DENIED = 'DENIED',
    BLOCKED = 'BLOCKED',
    LIMITED = 'LIMITED',
    UNAVAILABLRE = 'UNAVAILABLRE',
    UNDETERMINED = 'UNDETERMINED',
}